import os
from dotenv import load_dotenv
from anthropic import Anthropic
from backend.agents.state import FixerState
from backend.agents.utils import strip_code

load_dotenv()
#Loading the API key from the environment variables
client = Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))

def writer(state: FixerState) -> FixerState:
    #Writing the prompt for the AI
    prompt = f"""Write Python code for this task:

    {state['task']}

    Requirements:
    - Return ONLY the function definition(s) needed to solve the task.
    - Do NOT include any import statements unless the function genuinely requires them.
    - Do NOT include test code, example usage, print statements, or an "if __name__ == '__main__'" block.
    - Do NOT include explanations or markdown formatting.

    Output only the raw code."""
    response = client.messages.create(
        #Using the Claude Haiku model, with a maximum of 1000 tokens and a temperature of 0.0
        model="claude-haiku-4-5-20251001",
        max_tokens=1000,
        temperature=0.0,
        messages=[{"role": "user","content": prompt}]
    )
    #Storing the code in the state
    state["code"] = strip_code(response.content[0].text) #response.content[0].text is the code generated by the AI
    return state